### test the first url
GET http://localhost:3000/

### test the second url
GET http://localhost:3000/movies

### test query params
GET http://localhost:3000/movies?genre=Action

### test movie resource
GET http://localhost:3000/movies/a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d

### test post a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "year": 2008,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Action", "Crime", "Drama"],
  "rate": 9.0
}

### actualizar pelicula
PATCH http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
  "sql": "sql injection" 
}

### delete a movie
DELETE http://localhost:3000/movies/819923f6-e8bf-4ec4-8b12-2c16cd1f48cd